### ISSUE TITLE
How can I include it in a custom theme?

### ISSUE THREAD

**Issue by gree303** [pravams/magento-recurringorder#1]
Thanks for sharing. Tried it; but nothing changed after installation. Deleted cache + re-indexed, nothing there in frontend/backend.
Can you share some details to include it in a custom theme?
thank you

**Comment by pravams** [comment]
Which Magento version were you trying this on? This would work for only Magento 1 not Magento 2 version

**Comment by gree303** [comment]
Solved by copying module into custom theme. thanks.
